services:

  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: reexp
      MYSQL_USER: reexp
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - type: bind
        source: ./initdb/mysql
        target: /docker-entrypoint-initdb.d

  postgres:
    image: postgres
    shm_size: 128MB
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: pg
    volumes:
      - type: bind
        source: ./initdb/postgres
        target: /docker-entrypoint-initdb.d

